### ISSUE TITLE
Research of analytics in R from Java Code

### ISSUE THREAD

**Issue by pranasblk** [oracle/fastr#10]
I'd like to embed R code to my java project. Do you have some tutorial, pointers to existing code of enbeded R in Java, user guide, demo project or other documentation how to use R code (not standalone) from the system running core in written in Java.

Thanks!

**Comment by lukasstadler** [comment]
Hi! the API for embedding from Java has gotten a major overhaul very recently, a documentation draft is available at https://www.dropbox.com/s/aqy69srqki4g7hw/Embed%20Languages%20with%20the%20Graal%20Polyglot%20SDK.pdf?dl=0
I hope this helps - the examples are written for JavaScript, but they are equally applicable to R.

**Comment by lukasstadler** [comment]
Just let me know if something's unclear!

**Comment by armgong** [comment]
maybe renjin is another option?

**Comment by steve-s** [comment]
There is also a demo: https://github.com/graalvm/examples/tree/master/fastr_javaui

**Comment by steve-s** [comment]
Documentation is now available at http://www.graalvm.org/docs/reference-manual/languages/r/
