### ISSUE TITLE
Performance of data.table::fread

### ISSUE THREAD

**Issue by philippw1** [oracle/fastr#108]
Hi,

I am trying to read in a CSV file (roughly 530 MB) via a simple call of data.table::fread("test.csv"). However, computation (~4.5 minutes) was considerably slower compared to GNU-R on the same machine (~3 seconds). Am I missing something? Does anyone know what is happening here?
Thanks in advance!

**Comment by steve-s** [comment]
Hello philippw1,

thank you for the report. One issue specific to `data.table` is that it relies too much on GNU-R internals and emulating those internals faithfully enough comes at a cost.

Another problem is that currently in FastR the transitions between R extensions code (C/C++) and the R itself (e.g. in `Rf_length`) are very expensive compared to GNU-R. We are working this and the next release will contain preview of some major improvements, please stay tuned.

Once we are done with performance of R extensions in general, `data.table` (and `dplyr`...) is an obvious target for our performance tuning efforts.

Note: it is not the case of `fread`, which is mainly about IO optimizations I presume, but with FastR you often can get the same performance as `data.table` with just `base` R or plain old loops.

**Comment by philippw1** [comment]
Hi steve-s,
thanks for your quick reply. I am looking forward to the next release. Thanks for all the effort!
