### ISSUE TITLE
mx_copylib.py doesn't recoginze GNU ld scripts

### ISSUE THREAD

**Issue by hlolli** [oracle/fastr#110]
I noticed an error when recopy was called on libgcc_s.so that the file in my environment isn't a lib or symlink but a ld script file

```
cat /nix/store/rabiq4050h46lp96pas51vyjwsrvp94d-gfortran-8.3.0-lib/lib64/libgcc_s.so
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library.  */
GROUP ( libgcc_s.so.1 -lgcc )
```

easy to patch, but knowing to objdump `libgcc_s.so.1` instead of `libgcc_s.so` could prevent potential errors. But I'll admit that I didn't know about the existence of ld scripts until I bumped into this.

**Comment by steve-s** [comment]
Hello Hlöðver, 

thank you for your effort to bring FastR to the nix package manager! 

Which revision of FastR are you trying to compile? We have removed the capture and redistribution of GCC runtime libraries in 59177ac00edf1a3747025c7d644c2d7f63ab2feb. Instead, it will be the responsibility of the end-user to make sure they have `libgfortran3` (and also `libgomp1`, which we didn't capture and distribute even before) installed. Packages of this name should be available on Debian systems (tested on Ubuntu 18.04 and 19.04).

This makes the "just download and uncompresses" style installation a bit more tedious as it requires an additional step, but I guess it may work well with package managers that can just declare the respective runtime libraries as a dependency?

To your concrete question: AFAIK we deliberately ignored linker scripts and instead expected the user to provide a path to the "real" library `PKG_LDFLAGS_OVERRIDE`, but thinking about it now I am not sure how to make that work in your case. Did you patch this in some generic way?

**Comment by hlolli** [comment]
No I patched it very specifically :)

```patch
diff --git a/mx.fastr/mx_copylib.py b/mx.fastr/mx_copylib.py
index 4f57e1954..db45220d9 100644
--- a/mx.fastr/mx_copylib.py
+++ b/mx.fastr/mx_copylib.py
@@ -54,6 +54,9 @@ def _copylib(lib, libpath, plain_libpath_base, target):
     else:
         try:
             if platform.system() == 'Linux':
+                # https://github.com/oracle/fastr/issues/110
+                if libpath.endswith("libgcc_s.so"):
+                    libpath = libpath + ".1"
                 output = subprocess.check_output(['objdump', '-p', libpath])
             elif platform.system() == 'SunOS':
                 output = subprocess.check_output(['elfdump', '-d', libpath])

```

The battle is still ongoing, I'm compiling tag 19.2.1 for all the truffle/graal suite. I see that there's a lot of changes unmerged between master branch and the latest tag. For example I'm patching the unimplemented.c which is missing a lot of symbols. So far I've added these, some are on master and some not. I find it strange that `static` and `attribute_hidden` functions are being referenced in libR.so.

```c
double R_GE_VStrHeight(const char *s, cetype_t enc, const pGEcontext gc, pGEDevDesc dd) {
  unimplemented("R_GE_VStrHeight");
  return 0;
}

void R_GE_VText(double x, double y, const char * const s, cetype_t enc,
		double x_justify, double y_justify, double rotation,
		const pGEcontext gc, pGEDevDesc dd) {
  unimplemented("R_GE_VText");
}

double R_GE_VStrWidth(const char *s, cetype_t enc, const pGEcontext gc, pGEDevDesc dd) {
  unimplemented("R_GE_VStrWidth");
}

void setulb(int n, int m, double *x, double *l, double *u, int *nbd,
	    double *f, double *g, double factr, double *pgtol,
	    double *wa, int * iwa, char *task, int iprint, int *isave) {
  unimplemented("setulb");
}

void genptry(int n, double *p, double *ptry, double scale, void *ex) {
  unimplemented("genptry");
}

double EXP(double x) {
  unimplemented("EXP");
  return 0;
}

double LOG(double x) {
  unimplemented("LOG");
  return 0;
}

Rwchar_t Rf_utf8toucs32(wchar_t high, const char *s) {
  unimplemented("Rf_utf8toucs32");
  return 0;
}

size_t mbtoucs(unsigned int *wc, const char *s, size_t n) {
  unimplemented("mbtoucs");
  return (size_t) 0;
}


int DispatchOrEval(SEXP call, SEXP op, const char *generic, SEXP args,
		   SEXP rho, SEXP *ans, int dropmissing, int argsevald) {
  unimplemented("DispatchOrEval");
  return 0;
}
```

**Comment by steve-s** [comment]
We re-use some C code and all the R code of GNU-R's base libraries. Between the latest tag 19.2.x and what will be the next release 19.3.0 (now master) we upgraded those from GNU-R 3.5.1 to GNU-R 3.6.1, which means that, for example, some native functions have different arguments and things like that.

**Comment by hlolli** [comment]
Perfect, thank you for your help.

This seems to be running fine now, it was all inclusive mx build so it will
take some time until I can test the binary.

What was needed on top of what I mentioned earlier

```
void ENSURE_NAMEDMAX (SEXP x) {
  unimplemented("ENSURE_NAMEDMAX");
}

int Rf_AdobeSymbol2ucs2(int n) {
  unimplemented("Rf_AdobeSymbol2ucs2");
  return 0;
}
```

and libR.so loads fine.

**Comment by steve-s** [comment]
FYI: we've improved the documentation: https://github.com/oracle/fastr/blob/master/documentation/dev/building.md. At this point we plan to support only those GCC versions and distributions that we use for our builds, but I believe it will be more suitable for your use-case to not bundle the GCC runtime libraries with FastR as explained in the docs. Let us know if that does not work for you.
