### ISSUE TITLE
Installation of package fastRCluster lacks hints for troubleshooting

### ISSUE THREAD

**Issue by ceresek** [oracle/fastr#111]
I'm trying to use FastR through the fastRCluster package on Fedora Linux. I can install the package just fine, `installFastR` succeeds, even doing `x <- makeFastRCluster` succeeds, but any attempt to use the cluster (fastRClusterInstallPackages, clusterApply, clusterCall ...) ends with:

```
An internal error occurred.
Please report an issue at https://github.com/oracle/fastr including the commands. You can rerun FastR with --R.PrintErrorStacktracesToFile=true to turn on internal errors logging. Please attach the log file to the issue if possible.
Error in unserialize(node$con) : error reading from connection
```
I can launch the underlying FastR installation from its directory just fine.

I've noticed there is a `fastROptions` argument to `makeFastRCluster` (why not on `fastRClusterInstallPackages` ?), so I've tried to add the stack dump option, the resulting file is attached. (When the error message above gets displayed with `fastRClusterInstallPackages`, it is not clear where one should add the options.)

[fastr_errors_pid35459.log](https://github.com/oracle/fastr/files/3840359/fastr_errors_pid35459.log)

**Comment by ceresek** [comment]
This particular crash was caused by mismatch in serialization versions (the cluster master is R 3.6.1 which uses serialization version 3 by default, FastR 3.5.1 uses version 2). Setting R_DEFAULT_SERIALIZE_VERSION=2 in the environment removes the crash.

**Comment by steve-s** [comment]
Thank you for the report anyway. For future reference: we will support serialization version 3 in the next release.
