### ISSUE TITLE
Installation of package tidyverse fails due to missing OS-level dependencies

### ISSUE THREAD

**Issue by lhsvobodaj** [oracle/fastr#112]
I have a container running the image `oracle/graalvm-ce:19.2.1`. After installing FastR (`gu install R`), I was trying to install the package `tidyverse`.

However, due to some missing OS-level dependencies, the package installation failed. The missing dependencies are the following:

Package | Arch | Version | Repository | Size
---|---|---|---|---
bzip2 | x86_64 | 1.0.6-13.el7 | ol7_latest | 51 k
libxml2-devel | x86_64 | 2.9.1-6.0.1.el7_2.3 | ol7_latest | 1.0 M

Once I installed them, I was able to complete the `tidyverse` installation without any errors.

Considering the package `tidyverse` is widely used in R, shouldn't these two OS libraries be included in the GraalVM image or during FastR installation?

**Comment by steve-s** [comment]
Hello Luiz, 

thank you for letting us know. We will add this to the documentation at [graalvm.org](https://www.graalvm.org/docs/reference-manual/languages/r/), but we do not plan to distribute additional dependencies with FastR at this point.
