### ISSUE TITLE
Support for remote workers with fastRCluster ?

### ISSUE THREAD

**Issue by ceresek** [oracle/fastr#113]
Does fastRCluster support remote nodes ? I'm trying to do something like `x <- makeFastRCluster (master = 'master', names = c ('worker'))`, but this fails because `makeFastRCluster` passes `nnodes` in place of `names` to `psockClusterFactory` and that causes later call to `addClusterOptions` to fail.

I'm asking mainly to know if I should fix this locally and experiment more, or if remote nodes are not supported for some other, more fundamental reason, which I would eventually run into.

**Comment by steve-s** [comment]
This does look like an issue of `makeFastRCluster`. I am not aware of any reason why FastR couldn't work as a remote node, but we haven't tested that scenario yet.

**Comment by steve-s** [comment]
Fixed in https://github.com/oracle/fastr/pull/115
