### ISSUE TITLE
Unable to run 19.3.0 in Ubuntu 19.10 

### ISSUE THREAD

**Issue by davidpham87** [oracle/fastr#121]
Hello, 

I just desired to mention that `libgfortran3` is not available to Ubuntu 19.10. I tried to install it from previous distribution but I did not have much success (I could install the library but then I would get NaN all the time).

Best regards,
David

**Comment by steve-s** [comment]
Hello David, 

we tested the release on vanilla 19.04 and there the `libgfortran3` package was available. Maybe you can try using the package from 19.04? Another possibility could be copying the following libraries from GraalVM 19.2.0 (`jre/languages/R/lib`) to 19.3.0:

* libgcc_s.so
* libgcc_s.so.1
* libgfortran.so
* libgfortran.so.3
* libquadmath.so
* libquadmath.so.0

**Comment by davidpham87** [comment]
Hello Steve,

I wish I could copy them, but I erased my graalvm 19.2.0 folder once I installed the 19.3 (-_-')...

**Comment by steve-s** [comment]
> But you trick of putting the .so files to the new jre/languages/R/lib folder does not work. The configure script still does not detect the library. Guess I will stay in 19.2.1!

The `configure_fastr` is meant to help with setting up the system, but is not essential. It is possible that running `R`/`Rscript` would just work after this trick.

**Comment by minpet** [comment]
this issue is also true for Debian 10, as libgfortran3 is not available for it ... maybe you can look into upgrading the dependency if possible? Looks like version 3 is pretty old by now. On Debian 9 this is still available, though

**Comment by steve-s** [comment]
> maybe you can look into upgrading the dependency if possible

yes we are looking into that

**Comment by martijnburger** [comment]
I installed these two deps on Ubuntu 19.10 and R is working now (no need to configure_fastr):
https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/gcc-6-base_6.4.0-17ubuntu1_amd64.deb.html
https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libgfortran3_6.4.0-17ubuntu1_amd64.deb.html

**Comment by steve-s** [comment]
The latest release should work in Ubuntu 19.10 and other recent Linux distributions. Note that the requirements changed:

* Ubuntu 18.04 and 19.10: `apt-get install libgfortran-8-dev libgomp1`
* Oracle Linux 8: `yum install libgfortran`
* MacOS: `brew install gcc@4.9`

See the [updated documentation](https://www.graalvm.org/docs/reference-manual/languages/r/) for more details.
