### ISSUE TITLE
Polyglot value is not an object

### ISSUE THREAD

**Issue by querenker** [oracle/fastr#123]
Because polyglot values have a class attribute, I would assume that they are objects, but `is.object` returns `FALSE`.

```
> l <- eval.polyglot('python', '[1, 2, 3]')
> class(l)
[1] "polyglot.value"
> is.object(l)
[1] FALSE
```

As a result, internal generic functions can not be implemented for polyglot values (see #122)

**Comment by steve-s** [comment]
Hello Alexander, 

you stumbled upon the fact that some time ago we decided to treat the `polyglot.value` class as an "implicit" class, i.e., like `numeric` -- so `is.object` gives `FALSE` and internal generic functions ignore it [0]. After internal discussion, we decided that it makes sense to make it look like an explicit (user defined) class. Internal generic dispatch looks like a useful use-case for it. A PR that changes that should land soonish.

[0] for example:
```
> dim.numeric <- function(...) 42
> class(3)
[1] "numeric"
> dim(3)
NULL
> dim.myclass <- function(...) 42
> dim(structure(3, class='myclass'))
[1] 42
```
