### ISSUE TITLE
Incorrect formatting for sprintf %g and %G

### ISSUE THREAD

**Issue by ceresek** [oracle/fastr#126]
Standard R:
```
> sprintf ('%g', 0)
[1] "0"
```

FastR (19.2):
```
> sprintf ('%g', 0)
[1] "0.00000"
```

The documentation for `sprintf` states:

>      ‘g’, ‘G’ Double precision value, in ‘%e’ or ‘%E’ format if the
>           exponent is less than -4 or greater than or equal to the
>           precision, and ‘%f’ format otherwise.  (The precision
>           (default 6) specifies the number of _significant_ digits
>           here, whereas in ‘%f, %e’, it is the number of digits after
>           the decimal point.)

**Comment by steve-s** [comment]
Hello Petr,

thank you for the report. We can reproduce and will fix this. Please let us know in case this is a blocker issue for your use-case.

**Comment by steve-s** [comment]
The fix should land in the next release.
