### ISSUE TITLE
Incorrect documentation on building fastr release mode

### ISSUE THREAD

**Issue by janehmueller** [oracle/fastr#134]
Hey there,

I was trying to build fastr in release mode for graalvm 19.3.0. I used the documentation in [this repository](https://github.com/oracle/fastr/blob/master/documentation/dev/building.md), which (incorrectly) says:

> To build in release mode, set the FASTR_RELEASE environment variable to any value. Note that this can be done at any time without doing a complete clean and rebuild. Simply set the variable and execute mx build.

This however doesn't work:
```
env FASTR_RELEASE=123 mx --dy /vm graalvm-show
GraalVM distribution: GRAALVM_UNKNOWN_JAVA8
Version: 19.3.0
Config name: None
Components:
 - Truffle ('tfl', /truffle)
 - Component installer ('gu', /installer)
 - GraalVM license files ('gvm', /.)
 - LLVM.org toolchain ('llp', /llvm)
 - Truffle NFI ('nfi', /nfi)
 - Sulong ('slg', /llvm)
 - Graal SDK ('sdk', /graalvm)
Launchers:
 - gu (bash)
 - graalvm-native-clang++ (bash)
 - lli (bash)
 - graalvm-native-ld (bash)
 - graalvm-native-clang (bash)
 - polyglot (bash)
No library
Installables:
 - LLVM_TOOLCHAIN_INSTALLABLE_JAVA8
No standalone
```

The documentation in the [graal repository](https://github.com/oracle/graal/blob/master/vm/README.md) however gives the following instruction:
```
$ env FASTR_RELEASE=true mx --dynamicimports fastr,truffleruby,graalpython,/substratevm build
```

This does work:
```
env FASTR_RELEASE=true mx --dy /vm graalvm-show
GraalVM distribution: GRAALVM_UNKNOWN_JAVA8
Version: 19.3.0
Config name: None
Components:
 - Truffle ('tfl', /truffle)
 - Component installer ('gu', /installer)
 - GraalVM license files ('gvm', /.)
 - LLVM.org toolchain ('llp', /llvm)
 - Truffle NFI ('nfi', /nfi)
 - FastR ('R', /R)
 - Sulong ('slg', /llvm)
 - Graal SDK ('sdk', /graalvm)
Launchers:
 - gu (bash)
 - graalvm-native-clang++ (bash)
 - lli (bash)
 - graalvm-native-ld (bash)
 - graalvm-native-clang (bash)
 - polyglot (bash)
No library
Installables:
 - R_INSTALLABLE_JAVA8
 - LLVM_TOOLCHAIN_INSTALLABLE_JAVA8
No standalone
```

**Comment by steve-s** [comment]
Hello Jan, 

thank you for pointing that out. We will fix the documentation.

**Comment by steve-s** [comment]
Hello Jan, 

we've improved the build documentation: https://github.com/oracle/fastr/blob/master/documentation/dev/building.md. HTH
