### ISSUE TITLE
This should consider Renaming to graalr

### ISSUE THREAD

**Issue by frank-dspeed** [oracle/fastr#141]
At present there is an ongoing effort to create graalphp there exists graaljs, graalpython, graalwasm

I think this should get named graalr so it is more clear what this is truffle is a part of the GraalVM framework but I think it makes overall adoption more easy.

I raise a similar issue in truffleruby

**Comment by steve-s** [comment]
Hello Frank, 

I see the logic behind you suggestion, but at the same time, the name FastR is already established, used in slide-decks/blogs/... circulating around and so on, so we are not going to rename FastR at this point.

**Comment by frank-dspeed** [comment]
i have seen similar results in the truffleruby issue while they made me come anyway to the conclusion that truffle-r would be even more great and truffle-ruby truffle-js and node but anyway i think it is possible to setup a automated fork of this that renames that and maybe it will get more attraction then the old one and so super seed it.
