### ISSUE TITLE
Homebrew gcc@4.9 package upgraded to 4.9.4_2

### ISSUE THREAD

**Issue by fniephaus** [oracle/fastr#147]
fastr makes assumptions about the specific gcc version (see  `configure_fastr` for example). It currently expects `4.9.4_1` to be installed, but the Homebrew package has recently been upgraded to `4.9.4_2`. A symlink from `4.9.4_2` to `4.9.4_1` seems to work around the problem.

**Comment by sverrejb** [comment]
Adding to this, gcvc@4.9 is not supported at all on macOS Catalina.

**Comment by steve-s** [comment]
Hello, 

thank you for reporting this. In the next version, we are switching to GCC 8.3.0 on MacOS, but we will also ship the runtime libraries in FastR, so as long as you do not want to install an R package that contains Fortran code, there should be zero dependencies for FastR on MacOS from the next version (20.1.0). If you want to install a package with Fortran code, then you need GFotran (typically part of GCC package) of version 8.3.0 or any later version on MacOS.

This should be already the case in the dev builds of 20.1.0 and 20.2.0: https://github.com/graalvm/graalvm-ce-dev-builds/releases

For the record: on Linux it is going to be the same except that the minimal supported GCC version is 4.8.5 (i.e. the default version on Oracle Linux 7)

**Comment by fniephaus** [comment]
Fantastic, thanks!
