### ISSUE TITLE
FastR unique function performance 

### ISSUE THREAD

**Issue by akross** [oracle/fastr#154]
**Describe GraalVM and your environment :**

GraalVM version: graalvm-ce-java11-20.0.0
CE or EE: CE
JDK version: JDK11
OS and OS Version: macOS High Sierra
The output of java -Xinternalversion:
`OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for bsd-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 14:32:51 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)`

I'm trying to run this simple code in both FastR and R from CRAN

```
data <- read.csv2("data.csv", sep=';')
col_tbs<-c("SeasonID","gameweek","Team","Opponent","Home.Away","playerId","Role","total.matches")
left_join_base<-unique(data[,col_tbs])
```

data.csv is made of 67k rows and 137 columns.

The problem I'm facing is that running the code in FastR is much slower than R from CRAN.
FastR
```
user  system elapsed
801.035  11.902 870.111
```

CRAN
```
user  system elapsed 
  4.600   0.259   5.024 
```

The bottleneck seems to lie in the `unique` function. 
Are you aware of any issue around that? Maybe some misconfiguration? (I did run configure_fastr)

Thanks

**Comment by steve-s** [comment]
Hello, 

thank you for the report. We can reproduce the issue with this self contained reproducer:

```
l <- lapply(1:137, function(i) sample(1:10, 67000, replace=T))
names(l) <- paste0('col', 1:137)
df <- as.data.frame(l)
system.time(res <- unique(df[,paste0('col', 1:5)]))
```

the fix is on its way to the master branch.

**Comment by akross** [comment]
Thanks for looking into this Steve, I'll keep an eye on master to see when the fix will be released.

**Comment by steve-s** [comment]
The performance should be improved in 212b829695a3075e6c7426971225715f564c5654
