### ISSUE TITLE
Can't install package S4Vectors (Bioconductor)

### ISSUE THREAD

**Issue by hangyas** [oracle/fastr#164]
Installing the S4Vectors bioconductor package produces the following error:

```
Creating a generic function for ?complete.cases? from package ?stats? in package ?S4Vectors?
An internal error occurred: "java.lang.ArrayIndexOutOfBoundsException: -1"
```

reproduce:

```
R -e 'install.packages("BiocManager")'
R --R.PrintErrorStacktracesToFile=true -e 'BiocManager::install("S4Vectors")'
```

log: https://gist.github.com/hangyas/f145f557a5495ef86f72b2cbb5e92fa9

tested with `20.3.0-dev`

sessionInfo:
```
> sessionInfo()
FastR version 3.6.1 (2019-07-05)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /a/graalvm-ce-java8-20.3.0-dev/jre/languages/R/lib/libRblas.so
LAPACK: /a/graalvm-ce-java8-20.3.0-dev/jre/languages/R/lib/libRlapack.so

locale:
[1] UTF-8/UTF-8/UTF-8/C/UTF-8/UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
```

OS: docker ubuntu image + `Linux 572ace15b478 5.8.6-arch1-1 #1 SMP PREEMPT Thu, 03 Sep 2020 17:27:39 +0000 x86_64 x86_64 x86_64 GNU/Linux` (same error with the official graalvm image)

**Comment by steve-s** [comment]
Hello hangyas,

thank you for a detailed report. This is due to FastR not using internal dispatch for the `lengths` builtin. The fix is on its way.
