### ISSUE TITLE
Internal error trying to install the R validate package. 

### ISSUE THREAD

**Issue by rochifebo** [oracle/fastr#169]
Hi all, I have got an internal error trying to install the R validate package. 
Attached the log file.

Thank you in advance for your support.

[fastr_errors_pid26151.log](https://github.com/oracle/fastr/files/5480364/fastr_errors_pid26151.log)

**Comment by Akirathan** [comment]
Hello @rochifebo,
thank you for the report.

Fixed in [eca28](https://github.com/oracle/fastr/commit/eca2840c1196d64fd7be9a9b8a712efa1c383360).
