### ISSUE TITLE
incompatible types (from pairlist to list) in subassignment type fix

### ISSUE THREAD

**Issue by oroppas** [oracle/fastr#172]
I encountered the error while installing `surveillance`

```
> install.packages("surveillance")
```

Depending on gfortran version, you might need to set `FFLAGS = -O2 -mtune=native -fallow-argument-mismatch`
in `.R/Makevars` to force argument mismatch error into warning in gfortran-10. 

#### Can you reproduce with the latest development build?
Yes.

#### Include the following info

* GraalVM version or git revisions of FastR and GraalVM repositories if built from source.
```  
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 21.1.0-dev (build 11.0.9+10-jvmci-21.0-b03)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0-dev (build 11.0.9+10-jvmci-21.0-b03, mixed mode, sharing)
```
* `sessionInfo()`
```
FastR version 3.6.1 (2019-07-05)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /home/ryutas/graalvm-ce-java11-21.1.0-dev/languages/R/lib/libRblas.so
LAPACK: /home/ryutas/graalvm-ce-java11-21.1.0-dev/languages/R/lib/libRlapack.so

locale:
[1] UTF-8/UTF-8/UTF-8/C/UTF-8/UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] tools_3.6.1
```

**Comment by Akirathan** [comment]
The installation of `surveillance` package is fixed. However, we cannot guarantee that the package will be fully functional once installed. I tried running some demos of this package locally and noticed, that some of them fails - e.g. `cost` demo fails with argument mismatch, and `biosurvbook` fails with "Date and time conversion format 'G' is not implemented in FastR". But it might work correctly for your particular use case. In case you run into another failure, just post another issue and we will fix that.
