### ISSUE TITLE
When will there be a release for windows?

### ISSUE THREAD

**Issue by linpengcheng** [oracle/fastr#177]
When will there be a release for windows?

**Comment by steve-s** [comment]
Hello,

thank you for your interest in the project. There are no immediate plans for a Windows release at the moment. Note that you should be able to use FastR on windows via a Docker container or using the Linux subsystem for Windows.

**Comment by linpengcheng** [comment]
Thank you very much for your reply, I want to package it with the application and distribute it. It may be better that firstR for windows.
