### ISSUE TITLE
Incorrect number of arguments (5), expecting 4 for 'approxtest'

### ISSUE THREAD

**Issue by fniephaus** [oracle/fastr#186]
*(Tested on macOS Big Sur with GraalVM CE 21.1.0.)*

#### Repro
```bash
R -e 'install.packages("ggplot2")
R --jvm --polyglot
```
then
```R
library(ggplot2)
array <- eval.polyglot('js', '[4,1,3,1,4,1,4,2,5]')
size <- 9
values <- data.frame(x=1:size, y=array)
ggplot(values, aes(x=x, y=y, color=y)) +
    ggtitle("Foo") + labs(x="time", y="size") +
    theme(axis.text.x=element_blank()) +
    geom_point(size = .5, show.legend = FALSE) +
    scale_color_gradient(low = "#0091ff", high = "#f0650e")
```

#### Error
> Error: Error in .Call(C_ApproxTest, x, y, method, f, na.rm) :
>  Incorrect number of arguments (5), expecting 4 for 'approxtest'

#### Related Info
> `approxfun()` and `approx()` gain a new argument na.rm defaulting to true. If set to false, missing y values now propagate into the interpolated values.

[Source](https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf)

#### Workaround
Revert to CRAN snapshot from [2019-11-03](https://mran.microsoft.com/snapshot/2019-11-03) and reinstall ggplot2.

**Comment by Akirathan** [comment]
Hello @fniephaus. This is a known issue of ggplot2 version 3.3.3 that is in the newer 2021-02-01 MRAN snapshot. We are currently working on a fix for this package and it may get into GraalVM 21.3.0 release on the 19th of October.
