### ISSUE TITLE
Cannot install data.table package

### ISSUE THREAD

**Issue by vlulla** [oracle/fastr#19]
Trying to do `install.packages(c('data.table'))` I receive 
   ```
Error: package or namespace load failed for 'data.table' in runHook(".onLoad", env, package.lib, package):
     .onLoad failed in loadNamespace() for 'data.table', details:
      call: fun(libname, pkgname)
      error: Unexpected base R behaviour: list(x) has copied x
```
I suspect this is coming from https://github.com/Rdatatable/data.table/blob/master/R/onLoad.R#L71-L73 .

**Comment by steve-s** [comment]
Hi Vijay,

thank you for the report. This has been already reported as #16 . You can find more details there. For now, I am closing this as a duplicate.
