### ISSUE TITLE
Any plan for a Darwin aarch64 of FastR ?

### ISSUE THREAD

**Issue by scalastic** [oracle/fastr#198]
`GraalVM CE 22.2.0-dev` has already experimental `espresso`, `llvm-toolchain` and `native-image` components dedicated to the new ~~not so new~~ Apple Silicon ARM64 architecture. I've not found any info of such development on FastR side and `gu available r` returns `No components found.`

Is there any plan for such a version in the pipe ?
Thanks.

**Comment by steve-s** [comment]
Hello @scalastic,

there are no plans for Apple Silicon support in FastR for now.
