### ISSUE TITLE
Error installing tidyr

### ISSUE THREAD

**Issue by Mengzhiyaa** [oracle/fastr#199]
This with graal 22.1

I have install tidyr in fast and get the following error:

* installing *source* package ‘tidyr’ ...
** package ‘tidyr’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error in polyglot evaluation : /home/mzy/R/x86_64-pc-linux-gnu-library/fastr-22.1.0-4.0/00LOCK-tidyr/00new/tidyr/libs/tidyr.so: undefined symbol: SET_GROWABLE_BIT
ERROR: loading failed
* removing ‘/home/mzy/R/x86_64-pc-linux-gnu-library/fastr-22.1.0-4.0/tidyr’

and this is the output of session info:
> sessionInfo()
FastR version 4.0.3 (2020-10-10)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /home/mzy/biosoft/java/graalvm/graalvm-ce-java17-22.1.0/languages/R/lib/libRblas.so
LAPACK: /home/mzy/biosoft/java/graalvm/graalvm-ce-java17-22.1.0/languages/R/lib/libRlapack.so

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by Akirathan** [comment]
Hello @Mengzhiyaa, thanks for the report. We are already aware of this issue - we do not currently implement `SET_GROWABLE_BIT` C API function, which is also a blocker for `cpp11` package version 0.2.6, which is a transitive dependency for, e.g., `svglite` and `vroom` packages. This all means that it is pretty important to implement `SET_GROWABLE_BIT` function with respect to the compatibility with GNU-R. As soon as there will be a fix merged in `master`, I will paste the link in this discussion.

**Comment by Akirathan** [comment]
Fixed in https://github.com/oracle/fastr/commit/70638f3de30e88d827964cf94e51bdaf7338b0ca . `tidyr` can now be installed, along with `cpp11`.
