### ISSUE TITLE
Warning message in FastR not present in Gnu R

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#20]
The following code works fine in Gnu R:

library('dplyr')
ex = parse(text = ('cyl == 8'))
filter(mtcars, eval(ex))

In FastR it also works but gives the following warnings:

Warning messages:
1:
  SET_ATTRIB: tag in the attributes pairlist must be a symbol. NULL given.
2:
  SET_ATTRIB: tag in the attributes pairlist must be a symbol. NULL given.

**Comment by rbotafogo** [comment]
Now the following code works in Gnu R but does not work in FastR

library('dplyr')
library('nycflights13')

ex = parse(text = ("month == 1 & day == 1"))
filter(flights, eval(ex))

In FastR I get:

Warning messages:
1:
  SET_ATTRIB: tag in the attributes pairlist must be a symbol. NULL given.
2:
  SET_ATTRIB: tag in the attributes pairlist must be a symbol. NULL given.
Error: Can't bind data because it is not uniquely named
In addition: Warning message:
SET_ATTRIB: tag in the attributes pairlist must be a symbol. NULL given.

**Comment by steve-s** [comment]
Hi Rodrigo, 

thanks for the report. There are some known problems with `dplyr` also tracked by #13. We are planning to tackle them soon.

**Comment by steve-s** [comment]
Hi Rodrigo,

this concrete example should work with the current development version and in the next release (RC10). We're not passing all the `dplyr` tests, but getting closer.
