### ISSUE TITLE
Microsoft MRAN is no more, what are the alternatives?

### ISSUE THREAD

**Issue by manticore-projects** [oracle/fastr#214]
https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161

```
> install.packages('forecast');
Warning in install.packages("forecast") :
  'lib = "/usr/lib/jvm/java-17-graalvm/languages/R/library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) yes
Would you like to create a personal library
‘~/R/x86_64-pc-linux-gnu-library/fastr-23.0.0-4.0’
to install packages into? (yes/No/cancel) yes
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2021-02-01/src/contrib:
  mran.microsoft.com
```

And now, what please?

**Comment by manticore-projects** [comment]
Answering my own question, this seems to work:

1) Install `GroundHog` from https://groundhogr.com
2) find the relevant cut-off date, which is `2021-04-30` for R 4.0.3 (FastR)
3) generate the best Repo URL from POSIT: https://packagemanager.posit.co/client/#/repos/2/overview:

```R
options(repos = c(REPO_NAME = "https://packagemanager.posit.co/cran/2021-04-30"))
```

4) install the package via GroundHog for the given cut-off date

```R
library(groundhog)
groundhog.library("rio", "2021-04-30")
```

**Comment by tony-aw** [comment]
Hi,

You don't actually need groundhog. The RStudio/Posit packagemanager is already sufficient.

Kind regards,

Tony.

**Comment by steve-s** [comment]
Yes, FastR migrated to it in https://github.com/oracle/fastr/commit/37133d3374ff227bb3502440dbcd4533bf1732e7

**Comment by manticore-projects** [comment]
thank you!
