### ISSUE TITLE
Incorrect Tax calculation for Australia orders in Connector

### ISSUE THREAD

**Issue by Kirti-Ghuge** [oracle/fastr#218]
how to set an Australian Shopify NS connector site so the tax calc (GST) from Shopify (Shopify calc) flows through to NetSuite 

Is there any setting to override tax & accept Shopify tax calc or they need to perform something backend to override with Shopify calc into NS for Australia GST tax calc
the orders are not getting pushed to Netsuite troughing an error of amount mismatched, upon further investigation we come to the know that the issue is because of the tax rate as netsuite set the tax rate as 9.99 where it should be 10%  & when we do the calculation using 10% in Netsuite there is a difference of 0.01 you can check this on bellow screenshot fo the same order which we force post & corrected the tax rate to 10%.

**Comment by Kirti-Ghuge** [comment]
Earlier when we force post the Tax rate was 
<img width="587" alt="image" src="https://github.com/user-attachments/assets/be52957a-7753-44fd-9065-d44fcba13e58">
[Tax issue.docx](https://github.com/user-attachments/files/16506389/Tax.issue.docx)

**Comment by steve-s** [comment]
This is probably not the right place for this issue. It looks like an issue/request for either NetSuite (https://www.oracle.com/corporate/acquisitions/netsuite/support.html) or Shopify, seems like nothing to do with FastR (the R language implementation on GraalVM)
