### ISSUE TITLE
Can't load 'R.oo' package - 

### ISSUE THREAD

**Issue by kenahoo** [oracle/fastr#27]
When trying to install `R.oo` in FastR, I see the following:

```
> install.packages('R.oo')
Installing package into ‘/Users/kwilliams/git/hackday/graal-and-fastr/r-libs’
(as ‘lib’ is unspecified)
--2018-11-02 17:03:26--  https://cran.revolutionanalytics.com/src/contrib/R.oo_1.22.0.tar.gz
Resolving cran.revolutionanalytics.com (cran.revolutionanalytics.com)... 13.66.202.75
Connecting to cran.revolutionanalytics.com (cran.revolutionanalytics.com)|13.66.202.75|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 381495 (373K) [application/octet-stream]
Saving to: ‘/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/RtmpOiKhvT/downloaded_packages/R.oo_1.22.0.tar.gz’

/var/folders/zp/hj5hqfw970z0_78mrb_802l 100%[=============================================================================>] 372.55K  1.50MB/s    in 0.2s    

2018-11-02 17:03:27 (1.50 MB/s) - ‘/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/RtmpOiKhvT/downloaded_packages/R.oo_1.22.0.tar.gz’ saved [381495/381495]

* installing *source* package ‘R.oo’ ...
** package ‘R.oo’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘R.oo’ in runHook(".onAttach", ns, dirname(nspath), nsname):
 .onAttach failed in attachNamespace() for 'R.oo', details:
  call: getEnvironment.Package(this)
  error: could not find function "pos.to.env"
Error: loading failed
* DONE (R.oo)
```

No such error happens when doing the same in Gnu R.  `pos.to.env` is a function `base::pos.to.env`, so I'm not sure what's different about the namespaces that's causing it to not be found.

The `.onAttach()` function is doing this:

```
> R.oo:::.onAttach
function (libname, pkgname) 
{
    pkg <- get(pkgname, envir = getNamespace(pkgname))
    startupMessage(pkg)
}
```

And indeed when I run that internal code manually, it fails:

```
> pkgname <- 'R.oo'; pkg <- get(pkgname, envir = getNamespace(pkgname))
Error in getEnvironment.Package(this) :
  could not find function "pos.to.env"
```

**Comment by steve-s** [comment]
Hello Ken, 

thanks for the report. I can confirm that FastR indeed doesn't implement `pos.to.env` and we will get that fixed.

**Comment by kenahoo** [comment]
Thanks, Steve.  

I should also say that somehow after doing various other stuff in my session, that command `pkgname <- 'R.oo'; pkg <- get(pkgname, envir = getNamespace(pkgname))` actually started running without error (though I don't know whether it actually *succeeded*), not sure what's going on there.  When I restarted the session it went back to the failure behavior.

**Comment by steve-s** [comment]
Hi Ken, 

`pos.to.env` is implemented and we've also fixed one more issue that popped up during `R.oo` installation. The merge for the reference is 8364678079f1841bca3b7c16483914ffa2f88918

Note that this will propagate to the next public release. If you want to try the fixes now, you can use the community provided Dockerfile: https://github.com/nuest/fastr-docker

I've had some issues with running the `R.oo` tests, but I tried the sample below taken from the docs and it seems to work fine. Please, let us know if you find any other issues.

```
setConstructorS3("MyDouble", function(value=0, ...) {
  extend(as.double(value), "MyDouble", ...)
})
setMethodS3("as.character", "MyDouble", function(object, ...) {
  fmtstr <- attr(object, "fmtstr")
  if (is.null(fmtstr))
    fmtstr <- "%.6f"
  sprintf(fmtstr, object)
})
setMethodS3("print", "MyDouble", function(object, ...) {
  print(as.character(object), ...)
})
x <- MyDouble(3.1415926)
print(x)
x <- MyDouble(3.1415926, fmtstr="%3.2f")
print(x)
attr(x, "fmtstr") <- "%e"
print(x)
```
