### ISSUE TITLE
dimnames behavior different after dim is changed

### ISSUE THREAD

**Issue by comicfans** [oracle/fastr#34]
1. ary <- array(NA,dim=c(2,3,4),dimnames=list(1:2,1:3,1:4))
2. dim(ary) <- c(6,4)
3. dimnames(ary)[[2]] <- 1:4

fastR reports:  length of 'dimnames' [3] must match that of 'dims' [2]

after step 2
dimnames(ary) gives NULL on GNUR, but fastR gives
[[1]]
[1] "1" "2"

[[2]]
[1] "1" "2" "3"

[[3]]
[1] "1" "2" "3" "4"

seems that fastR still preserve old dimnames even array dim is changed

**Comment by steve-s** [comment]
Hi comicfans,

thank you for the report and small reproducible example. It seems to boil down to:
```
x <- NULL
x[[2]] <- 1:4
x
```
In `x[[2]] <- 1:4` GNU-R just extends the list with `NULL`s. We're working on the fix in FastR.

**Comment by steve-s** [comment]
Should be fixed in a03bc4284850f5cadba9a5cba69add9f024f23b8
