### ISSUE TITLE
PolyglotException when calling from clojure

### ISSUE THREAD

**Issue by 573** [oracle/fastr#37]
When trying to call ruby from a leiningen session I get the folowing error:

> PolyglotException java.lang.NullPointerException  com.oracle.truffle.r.runtime.ffi.DLL$DLLInfo.access$1000 (DLL.java:201)

Initialized as follows (source: https://blog.taylorwood.io/2018/11/26/graal-polyglot.html):

    user=> (ns polydact.core
    user=> (:import (org.graalvm.polyglot Context Value)
    user=>          (org.graalvm.polyglot.proxy ProxyArray ProxyExecutable ProxyObject)))
    polydact.core=> (def context (-> (Context/newBuilder (into-array ["R"]))
    polydact.core=> (.allowAllAccess true)
    polydact.core=> (.build)))
    polydact.core=> (.eval context "R" "
    polydact.core=> 3^2 + 2^2
    polydact.core=> ")

**Comment by steve-s** [comment]
Could not reproduce
