### ISSUE TITLE
An internal error occurred: "java.lang.AssertionError: Drop: expected String or RAbstractStringVector in dimnames"

### ISSUE THREAD

**Issue by comicfans** [oracle/fastr#38]
calling following code leads fastR error:

```R
 library(TTR)
 ary <- array(1,dim=c(2,2),dimnames=list(c('2018-01-01','2018-01-02'),c('high','low')))
 SAR(ary)
```

full log 
[fastr_errors_pid18181.log](https://github.com/oracle/fastr/files/2636757/fastr_errors_pid18181.log)

**Comment by steve-s** [comment]
Hi comicfans,

thank you for the report. Should be fixed by 140a4badf40eb445ac6f9cb0cb57beb4fca9c95e
