### ISSUE TITLE
Language ID inconsistent?

### ISSUE THREAD

**Issue by fniephaus** [oracle/fastr#45]
To my knowledge, fastr is the only Truffle language that uses a capital letter as language ID. Example:
```bash
$ gu available
Downloading: Component catalog
ComponentId              Version             Component name
----------------------------------------------------------------
python                   1.0.0-rc10          Graal.Python
R                        1.0.0-rc10          FastR
ruby                     1.0.0-rc10          TruffleRuby
```

This inconsistency is especially noticeable when using the polyglot API.

I would suggest to use a lowercase `r` for consistency reasons instead. At the same time, I think it would be reasonable to make language IDs case-insensitive in Truffle, which would solve the backward compatibility issue and increases usability in general.

**Comment by steve-s** [comment]
Hi Fabio,

thank you for the suggestion. We'll discuss it internally.

**Comment by steve-s** [comment]
Hi Fabio,

so the conclusion is that R is somewhat special since it is a single letter name, so we won't be changing its name in the metadata. `gu` is already case insensitive.

**Comment by fniephaus** [comment]
Hi Steve,
Thanks for the follow-up. Does this mean I will also be able to use a lowercase 'r' when interacting with the Polyglot API (e.g. Polyglot.eval('r', code...)) at some point?

**Comment by steve-s** [comment]
> Does this mean I will also be able to use a lowercase 'r' when interacting with the Polyglot API

I don't think this is planned. This would be more of a question for Truffle framework.
