### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#50]
The following code has a bug... in 'mutate', 'gain_per_hour' uses 'hour' in the formula instead of 'hours'.  Using 'hours' gives the right result. 

    library('dplyr')
    library('nycflights13')

    flights_sml =
      flights %>%
        select(year: day,
               ends_with("delay"),
               distance,
               air_time)

    print(flights_sml)

    mu = flights_sml %>%
      mutate(gain = arr_delay - dep_delay,
                  hours = air_time / 60,
                  gain_per_hour = gain / hour)

    print(mu)

and this is the stack trance:

RuntimeError:
  java.lang.ArrayIndexOutOfBoundsException: -1 (RInternalError)
  	from com.oracle.truffle.r.nodes.function.FunctionDefinitionNode.execute(FunctionDefinitionNode.java:325)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:275)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:264)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:251)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:233)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:216)
  	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:84)
  	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
  	from com.oracle.truffle.r.nodes.function.call.CallRFunctionNode.execute(CallRFunctionNode.java:59)
  	from com.oracle.truffle.r.nodes.function.RCallNode$DispatchedCallNode.execute(RCallNode.java:1169)
  Caused by:
  -1 (ArrayIndexOutOfBoundsException)
  	from java.util.ArrayList.elementData(ArrayList.java:422)
  	from java.util.ArrayList.remove(ArrayList.java:499)
  	from com.oracle.truffle.r.ffi.impl.common.JavaUpCallsRFFIImpl.Rf_unprotect(JavaUpCallsRFFIImpl.java:1572)
  	from com.oracle.truffle.r.ffi.impl.upcalls.Rf_unprotectCall$Rf_unprotectCallFactory$1.execute(Rf_unprotectCall.java:54)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:275)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:264)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:251)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:233)
  	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:216)
  	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:84)

**Comment by steve-s** [comment]
Hi Rodrigo, 

thank you for the report. We can reproduce the issue and are working on a fix.

**Comment by steve-s** [comment]
Should be fixed in d8bb26771d3e952f627ad01f552eebc864c5d42c
