### ISSUE TITLE
Wrong result when working with integer number (RC11)

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#51]
The following code does not work properly:

    library('dplyr')
    library('nycflights13')

    fl = flights %>%
          transmute(dep_time,
                    hour = dep_time %/% 100L,
                    minute = dep_time %% 100L)

    print(fl)

It returns

# A tibble: 336,776 x 3
   dep_time  hour minute
      <int> <int>  <int>
 1        5     5      5
 2        5     5      5
 3        5     5      5
 4        5     5      5
 5        5     5      5
 6        5     5      5
 7        5     5      5
 8        5     5      5
 9        5     5      5
10        5     5      5

'dep_time' was changed even though there is no command to change it.  

If this code is executed the first time in the R session without the 'L', then we get:

# A tibble: 336,776 x 3
   dep_time  hour minute
      <int> <dbl>  <dbl>
 1      517     5     17
 2      533     5     33
 3      542     5     42
 4      544     5     44
 5      554     5     54
 6      554     5     54
 7      555     5     55
 8      557     5     57
 9      557     5     57
10      558     5     58

Which is the expected result.

Now, if running the code again with the 'L', after having executed it without the 'L', it works fine.

However, if we first execute the code with the 'L', then execute again without the 'L' both come out wrong.

**Comment by steve-s** [comment]
Hi Rodrigo, 

thank you for the report. We can reproduce and are working on a fix.

**Comment by steve-s** [comment]
Should be fixed in d8bb26771d3e952f627ad01f552eebc864c5d42c
