### ISSUE TITLE
Problem with finding right generic method by its signature

### ISSUE THREAD

**Issue by webii** [oracle/fastr#55]
I tried to run some code using `raster` library and found some problems with method properties.

So to reproduce the problem I got some code:
```
setGeneric("testMe", function(x, y) standardGeneric("testMe"))

setMethod("testMe", signature(x='missing', y='character'),
function(y) {
	print(as.list(environment()))

	testMe(x = y)
})

setMethod("testMe", signature(x='character', y='missing'),
function(x) {
	print(x)
})

testMe(y='not working')

```

On standard R the output will is:

```
$y
[1] "not working"

[1] "not working"
```

But on fastR:

```
$x
[1] "not working"

$y
` `

Error in testMe(x = y) : argument "y" is missing, with no default
```

So, raster library have a lot of `setMethods` with different signatures and because of this problem there is no way to read any raster map.

**Comment by steve-s** [comment]
Hello Michał, 

thank you for the bug report with a small reproducible example. We can reproduce and are working on a fix.
