### ISSUE TITLE
different behavior when calling as.Date with invalid date string

### ISSUE THREAD

**Issue by comicfans** [oracle/fastr#56]
with GNU-R
> as.Date('2017-02-29')
Error in charToDate(x) :
  character string is not in a standard unambiguous format

with fastr
> as.Date('2017-02-29')
[1] "2017-02-28"
>

**Comment by steve-s** [comment]
Hi comicfans, 

thank you for the report. We can reproduce and are working on a fix.

**Comment by steve-s** [comment]
this should be fixed now
