### ISSUE TITLE
different behavior when calling tcrossprod from apply 

### ISSUE THREAD

**Issue by comicfans** [oracle/fastr#60]
GNU-R
>apply(array(NA,dim=c(2,1)), 2 ,tcrossprod)
     [,1]
[1,]   NA
[2,]   NA
[3,]   NA
[4,]   NA

fastR
> apply(array(NA,dim=c(2,1)), 2 ,tcrossprod)
Error in tcrossprod(x, y) : non-conformable arguments

**Comment by steve-s** [comment]
Hello comicfans, 

thank you for another nice and small reproducible example! It should be fixed now.
