### ISSUE TITLE
Tibble does not print properly when using knitr

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#68]
I'm trying to print a tibble in knitr.  This is the result:

    df <- tibble(x = 1:3, y = 3:1)
    print(df)
    ## Warning in max(tier_widths): no non-missing arguments to max; returning - 
    ## Inf

    ## Warning in max(tier_widths): no non-missing arguments to max; returning - 
    ## Inf
    ## [38;5;246m# A tibble: 3 x 2[39m
    ## [38;5;246m# … with 2 more variables: x [3m[38;5;246m<int>[38;5;246m[23m, y 
    [3m[38;5;246m<int>[38;5;246m[23m[39m

I've google it and it seems that this also used to happen in Rstudio, that had to be patched, but I couldn't find what was done.

**Comment by steve-s** [comment]
Hello Rodrigo, 

thank you for the report. We can reproduce and are working on a fix.

**Comment by steve-s** [comment]
Hi Rodrigo, 

FastR's fixes and features are not back-ported for now until FastR is in experimental state, so you will have to wait for 19.3.0. We are working on publicly providing nightly/weekly builds of the development version of GraalVM for testing. Please re-open if this still doesn't work in 19.3.0
