### ISSUE TITLE
Cannot load 'rake' in Polyglot code through R

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#75]
I've put the following line in an Rscript and 'rake' is an installed Ruby gem:

     eval.polyglot("ruby", "require %q(rake)")

and it gives me the following error:

    Error in polyglot evaluation : Coercion error: nil.to_str => String failed (TypeError)
	    at <ruby> null(Unknown)

Now, if instead of 'rake' I try to load 'stringio', it works fine and returns [TRUE]

**Comment by eregon** [comment]
Thank you for the report.
I believe this is the same issue as https://github.com/oracle/truffleruby/issues/1653 which will be fixed in the next release.
