### ISSUE TITLE
Plotly not working

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#78]
I tried to run Ploty and got the following error:

RuntimeError:
  Error: No Cairo or bitmap device is available. Such a graphics device is required to convert sizes correctly in ggplotly().

   You have two options:
    (1) install.packages('Cairo')
    (2) compile R to use a bitmap device (png or jpeg) (RError)
  Translated to internal error

Since fastR supports 'png' and 'jpeg' should condition 2 be satisfied?

Thanks

**Comment by steve-s** [comment]
Hello Rodrigo, 

thank you for the report. We could reproduce the issue. The fix is already queued in our internal system. I've tried the following example from `plotly` and it seems to work fine:
```
plot_ly(z = ~volcano, type = "surface")
```
