### ISSUE TITLE
Crash when running simple script

### ISSUE THREAD

**Issue by bobjansen** [oracle/fastr#83]
The following script (taken from [BrodieG's blog](https://www.brodieg.com/2019/06/10/base-vs-data-table/)) will reliably crash the interpreter (on my machine) in the final code block. Using smaller sizes for `n` and `n.grp` helps but these objects should fit easily?

```
sys.time <- system.time
# Setup ----
RNGversion("3.5.2"); set.seed(42)
n     <- 1e7
n.grp <- 1e6
grp   <- sample(n.grp, n, replace=TRUE)
noise <- rep(c(.001, -.001), n/2)  # more on this later
x     <- runif(n) + noise
y     <- runif(n) + noise          # we'll use this later

sys.time({
  o <- order(grp)
  go <- grp[o]
  xo <- x[o]

  grp.dat <- split(xo, go)
  xgo.sum <- vapply(grp.dat, sum, numeric(1))
})

sys.time(u2 <- go[c(TRUE, go[-1L] != go[-length(go)])])

# Group sums ----
sys.time({
  o <- order(grp)
  x.rs <- rowsum(x[o], grp[o], reorder=FALSE)
})
``` 
Might be related to #79 but this one seems at least simpler to debug. Log:
[hs_err_pid14389.log](https://github.com/oracle/fastr/files/3277593/hs_err_pid14389.log)

Memory use when idle:
```
➜  ~ free -m
              total        used        free      shared  buff/cache   available
Mem:          15993        7605        3383         149        5003        7909
Swap:         16383           0       16383
```

**Comment by steve-s** [comment]
Hello Bob, 

thank you for reporting this. I've tried on the current development version and it seems to work. It indeed looks like #79. You can try the development version with this docker image: https://github.com/nuest/fastr-docker.
