### ISSUE TITLE
Bug in `readr` read_csv 

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#87]
I have the following csv file:

    ID
    1

Run:

    > fin = read.csv("finance.csv")
    > fin
       X.ID
    1    1

Now run:

    > library('readr')
    > fin = read_csv("finance.csv")
    Parsed with column specification:
    cols(
      ID = col_double()
    )
    > fin
    Error in is.character(j) : argument "x" is missing, with no default

**Comment by zslajchrt** [comment]
Hi,

I managed to reproduce and fix the problem.

Thanks for the report.

Zbyněk Šlajchrt

út 6. 8. 2019 v 16:46 odesílatel Rodrigo Botafogo <notifications@github.com>
napsal:
