### ISSUE TITLE
Types differ between fastR and GnuR when reading data

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#88]
This is the input file:

# finance.csv
ID;CONTA_INVESTIMENTO;Data;Quantidade_Cotas;Valor_Cota;Valor_Nominal;Valor_R$;IR_IOF;Valor_Liquido;Percent;Diferenca
1;PETR4;04/12/2018;120,00;21,53;2583,60;2583,60;;2583,60;;
2;PINE4;04/12/2018;127,00;2,29;290,83;290,83;;290,83;;
3;B2W - Companhia Digital;04/12/2018;50,00;39,36;1968,00;1968,00;;1968,00;;
4;Embraer SA;04/12/2018;200,00;21,40;4280,00;4280,00;;4280,00;;
5;Eternit SA;04/12/2018;66,00;2,75;181,50;181,50;;181,50;;

Reading it in gnuR:

> finance = read.csv2('finance.csv')
> str(finance)
'data.frame':	5 obs. of  11 variables:
 $ ID                : int  1 2 3 4 5
 $ CONTA_INVESTIMENTO: Factor w/ 5 levels "B2W - Companhia Digital",..: 4 5 1 2 3
 $ Data              : Factor w/ 1 level "04/12/2018": 1 1 1 1 1
 $ Quantidade_Cotas  : num  120 127 50 200 66
 $ Valor_Cota        : num  21.53 2.29 39.36 21.4 2.75
 $ Valor_Nominal     : num  2584 291 1968 4280 182
 $ Valor_R.          : num  2584 291 1968 4280 182
 $ IR_IOF            : logi  NA NA NA NA NA
 $ Valor_Liquido     : num  2584 291 1968 4280 182
 $ Percent           : logi  NA NA NA NA NA
 $ Diferenca         : logi  NA NA NA NA NA

Now reading in fastR:

> finance = read.csv2("finance.csv")
> str(finance)
'data.frame':	5 obs. of  11 variables:
 $ X.ID              : int  1 2 3 4 5
 $ CONTA_INVESTIMENTO: Factor w/ 5 levels "B2W - Companhia Digital",..: 4 5 1 2 3
 $ Data              : Factor w/ 1 level "04/12/2018": 1 1 1 1 1
 $ Quantidade_Cotas  : Factor w/ 5 levels "120,00","127,00",..: 1 2 4 3 5
 $ Valor_Cota        : Factor w/ 5 levels "2,29","2,75",..: 4 1 5 3 2
 $ Valor_Nominal     : Factor w/ 5 levels "181,50","1968,00",..: 3 4 2 5 1
 $ Valor_R.          : Factor w/ 5 levels "181,50","1968,00",..: 3 4 2 5 1
 $ IR_IOF            : logi  NA NA NA NA NA
 $ Valor_Liquido     : Factor w/ 5 levels "181,50","1968,00",..: 3 4 2 5 1
 $ Percent           : logi  NA NA NA NA NA
 $ Diferenca         : logi  NA NA NA NA NA

**Comment by zslajchrt** [comment]
The problem identified and fixed.

**Comment by zslajchrt** [comment]
Just keep in mind that now the the number format used in csv must be compatible with the current locale. If needed, the locale can be changed as follows:
```
Sys.setlocale("LC_NUMERIC", "pt_BR")
```
