### ISSUE TITLE
fastr, truffleruby, graalpython and graal-native-image 19.2.0 have top-level license files as copies instead of symlinks

### ISSUE THREAD

**Issue by lucaswerkmeister** [oracle/fastr#90]
Hi folks! This potential issue in the release process seems to affect fastr, truffleruby and graalpython equally, but I’m arbitrarily reporting it here. Let me know if there’s a better place.

In previous releases, the JAR files contained top-level entries `LICENSE_FASTR.txt` and `3rd_party_licenses_fastr.txt` (under different names for truffleruby and graalpython, of course) as symlinks into files of the same name in `jre/languages/R/` (or other language subdirectories), as indicated by the `META-INF/symlinks` (lists the symlink) and `META-INF/permissions` (symlinks have permission `rwxrwxrwx`) files.

In 19.2.0, those top-level files became proper copies: they exist in the JAR file, have  `rw-r--r--` in the permissions file and are no longer listed in the symlinks file. The old symlink targets still exist, though, apparently identical (though I didn’t diff all six pairs).

This isn’t really a problem, but it tripped up the Arch AUR packages while I was trying to update them (they only used to copy `jre/` into the target directory and then create the symlinks, now the top-level license files also need to be copied so the permissions can be applied); and while I can work around that, I just wanted to check with you if that’s an intentional change or if anything went wrong during the release process and the symlinks turned into copies accidentally.

**Comment by lucaswerkmeister** [comment]
Update: graal-native-image is also affected (didn’t check that one yesterday).

**Comment by gilles-duboscq** [comment]
Hey Lucas,

Thank you for the report.
This is an intentional change so the license file is visible at the root even when the JAR is extracted with standard tools (the symlink only exists in some custom graalvm metadata).
It would complicate things a bit to reverse the symlink (i.e., have `jre/languages/R/LICENSE_FASTR.txt` be a symlink to `../../../LICENSE_FASTR.txt`) so i would not change anything unless it really makes your work easier.

**Comment by lucaswerkmeister** [comment]
No problem, then I’ll just update my build files :) thanks!
